# Generated by Django 5.2.6 on 2026-06-12 08:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_staffprofile_date_of_birth_staffprofile_middle_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_category', models.CharField(choices=[('AUTH', 'Authentication'), ('CRUD', 'CRUD Activity'), ('SYSTEM', 'System'), ('SECURITY', 'Security')], default='AUTH', max_length=20)),
                ('event_type', models.CharField(choices=[('LOGIN_SUCCESS', 'Login Success'), ('LOGIN_FAILED', 'Login Failed'), ('LOGOUT', 'Logout'), ('CREATE', 'Create'), ('READ', 'Read'), ('UPDATE', 'Update'), ('DELETE', 'Delete')], max_length=50)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed')], max_length=20)),
                ('username_attempted', models.CharField(blank=True, help_text='Username/email submitted during login attempt.', max_length=255)),
                ('app_label', models.CharField(blank=True, help_text='For future CRUD logs, e.g. crm, procurement, ledger.', max_length=100)),
                ('resource', models.CharField(blank=True, help_text='For future CRUD logs, e.g. party, clientrequest, transaction.', max_length=100)),
                ('action', models.CharField(blank=True, help_text='For future CRUD logs, e.g. create, view, edit, delete.', max_length=100)),
                ('object_id', models.CharField(blank=True, help_text='Affected object ID for future CRUD logs.', max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Extra details such as error reason, request path, etc.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='audit_user_created_idx'), models.Index(fields=['event_type', '-created_at'], name='audit_event_created_idx'), models.Index(fields=['event_category', '-created_at'], name='audit_cat_created_idx')],
            },
        ),
    ]
