# Generated by Django 5.2.6 on 2026-06-19 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_passwordresetcode_auditlog_target_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='event_type',
            field=models.CharField(choices=[('LOGIN_SUCCESS', 'Login Success'), ('LOGIN_FAILED', 'Login Failed'), ('LOGOUT', 'Logout'), ('ACCOUNT_CREATED', 'Account Created'), ('DEFAULT_PASSWORD_LOGIN_BLOCKED', 'Default Password Login Blocked'), ('PASSWORD_RESET_LINK_SENT', 'Password Reset Link Sent'), ('PASSWORD_RESET_CODE_VERIFIED', 'Password Reset Code Verified'), ('PASSWORD_RESET_COMPLETED', 'Password Reset Completed'), ('PASSWORD_RESET_FAILED', 'Password Reset Failed'), ('PASSWORD_RESET_REQUESTED', 'Password Reset Requested'), ('PASSWORD_RESET_EMAIL_FAILED', 'Password Reset Email Failed'), ('CREATE', 'Create'), ('READ', 'Read'), ('UPDATE', 'Update'), ('DELETE', 'Delete')], max_length=80),
        ),
    ]
