# Generated by Django 5.2.6 on 2026-06-28 19:56

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_auditlog_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='reports_to',
            field=models.ForeignKey(blank=True, help_text="The staff member's immediate reporting manager.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_reports', to='accounts.staffprofile'),
        ),
        migrations.CreateModel(
            name='DepartmentLeadership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('leadership_type', models.CharField(choices=[('MANAGER', 'Manager'), ('DEPUTY', 'Deputy Manager')], default='MANAGER', max_length=20)),
                ('is_primary', models.BooleanField(default=False, help_text='Identifies the principal leader for the department.')),
                ('active_from', models.DateField(default=django.utils.timezone.localdate)),
                ('active_until', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_department_leaderships', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leadership_assignments', to='accounts.department')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='department_leaderships', to='accounts.staffprofile')),
            ],
            options={
                'verbose_name': 'Department Leadership',
                'verbose_name_plural': 'Department Leadership',
                'ordering': ['department__name', '-is_primary', 'manager__user__first_name'],
                'permissions': [('manage_departmentleadership', 'Can manage department leadership')],
                'constraints': [models.CheckConstraint(condition=models.Q(('active_until__isnull', True), ('active_until__gte', models.F('active_from')), _connector='OR'), name='acct_leadership_dates_valid'), models.UniqueConstraint(fields=('department', 'manager', 'leadership_type', 'active_from'), name='acct_unique_leadership_term'), models.UniqueConstraint(condition=models.Q(('active_until__isnull', True), ('is_primary', True)), fields=('department',), name='acct_one_open_primary_lead')],
            },
        ),
    ]
