# Generated by Django 5.2.6 on 2026-06-28 20:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0007_staffprofile_reports_to_departmentleadership'),
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assignee_name', models.CharField(blank=True, max_length=255)),
                ('assignee_email', models.EmailField(blank=True, max_length=254)),
                ('assignee_employee_id', models.CharField(blank=True, max_length=50)),
                ('assigned_department_name', models.CharField(blank=True, max_length=150)),
                ('assigned_department_code', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('TO_DO', 'To do'), ('IN_PROGRESS', 'In progress'), ('BLOCKED', 'Blocked'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='TO_DO', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('archived_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_tasks', to=settings.AUTH_USER_MODEL)),
                ('assigned_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to='accounts.department')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'permissions': [('assign_task', 'Can assign tasks'), ('cancel_task', 'Can cancel tasks'), ('archive_task', 'Can archive tasks'), ('restore_task', 'Can restore archived tasks'), ('view_department_task', 'Can view department tasks'), ('assign_department_task', 'Can assign department tasks'), ('manage_department_task', 'Can manage department tasks'), ('view_all_task', 'Can view all tasks'), ('assign_all_task', 'Can assign tasks across the organisation'), ('manage_all_task', 'Can manage all organisation tasks')],
                'default_permissions': ('add', 'change', 'view'),
            },
        ),
        migrations.CreateModel(
            name='TaskBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('assignment_type', models.CharField(choices=[('PERSONAL', 'Personal'), ('USERS', 'Selected staff'), ('DEPARTMENT', 'Department')], db_index=True, max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], db_index=True, default='MEDIUM', max_length=20)),
                ('start_at', models.DateTimeField(blank=True, null=True)),
                ('due_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('source_department_name', models.CharField(blank=True, max_length=150)),
                ('source_department_code', models.CharField(blank=True, max_length=20)),
                ('created_by_name', models.CharField(blank=True, max_length=255)),
                ('created_by_email', models.EmailField(blank=True, max_length=254)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('archived_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_task_batches', to=settings.AUTH_USER_MODEL)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_task_batches', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_task_batches', to=settings.AUTH_USER_MODEL)),
                ('source_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_batches', to='accounts.department')),
            ],
            options={
                'ordering': ['-created_at'],
                'default_permissions': ('add', 'change', 'view'),
            },
        ),
        migrations.CreateModel(
            name='TaskActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('BATCH_CREATED', 'Task batch created'), ('BATCH_UPDATED', 'Task batch updated'), ('BATCH_CANCELLED', 'Task batch cancelled'), ('BATCH_ARCHIVED', 'Task batch archived'), ('BATCH_RESTORED', 'Task batch restored'), ('TASK_CREATED', 'Task created'), ('TASK_ASSIGNED', 'Task assigned'), ('TASK_REASSIGNED', 'Task reassigned'), ('TASK_DETAILS_UPDATED', 'Task details updated'), ('STATUS_CHANGED', 'Task status changed'), ('TASK_CANCELLED', 'Task cancelled'), ('TASK_ARCHIVED', 'Task archived'), ('TASK_RESTORED', 'Task restored'), ('COMMENT_ADDED', 'Comment added'), ('COMMENT_EDITED', 'Comment edited'), ('COMMENT_REMOVED', 'Comment removed'), ('REMINDER_CREATED', 'Reminder created'), ('REMINDER_UPDATED', 'Reminder updated'), ('REMINDER_CANCELLED', 'Reminder cancelled'), ('REMINDER_SENT', 'Reminder sent'), ('NOTIFICATION_CREATED', 'Notification created')], db_index=True, max_length=40)),
                ('previous_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_activities', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activities', to='tasks.task')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activities', to='tasks.taskbatch')),
            ],
            options={
                'ordering': ['-created_at'],
                'default_permissions': ('view',),
            },
        ),
        migrations.AddField(
            model_name='task',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='tasks.taskbatch'),
        ),
        migrations.CreateModel(
            name='TaskComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body', models.TextField()),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('removed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('removal_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_comments', to=settings.AUTH_USER_MODEL)),
                ('removed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='removed_task_comments', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comments', to='tasks.task')),
            ],
            options={
                'ordering': ['created_at'],
                'permissions': [('moderate_taskcomment', 'Can remove task comments')],
                'default_permissions': ('add', 'change', 'view'),
            },
        ),
        migrations.CreateModel(
            name='TaskReminder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('remind_at', models.DateTimeField(db_index=True)),
                ('channels', models.JSONField(default=list)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_task_reminders', to=settings.AUTH_USER_MODEL)),
                ('notification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_reminders', to='notifications.notification')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reminders', to='tasks.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_reminders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['remind_at'],
                'default_permissions': ('add', 'change', 'view'),
            },
        ),
        migrations.AddIndex(
            model_name='taskbatch',
            index=models.Index(fields=['assignment_type', 'priority', '-created_at'], name='task_batch_type_prio_idx'),
        ),
        migrations.AddIndex(
            model_name='taskbatch',
            index=models.Index(fields=['created_by', 'archived_at', '-created_at'], name='task_batch_creator_idx'),
        ),
        migrations.AddIndex(
            model_name='taskbatch',
            index=models.Index(fields=['source_department', 'archived_at', '-created_at'], name='task_batch_dept_idx'),
        ),
        migrations.AddConstraint(
            model_name='taskbatch',
            constraint=models.CheckConstraint(condition=models.Q(('start_at__isnull', True), ('due_at__isnull', True), ('due_at__gte', models.F('start_at')), _connector='OR'), name='task_batch_dates_valid'),
        ),
        migrations.AddConstraint(
            model_name='taskbatch',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('cancellation_reason', ''), ('cancelled_at__isnull', True)), models.Q(('cancelled_at__isnull', False), models.Q(('cancellation_reason', ''), _negated=True)), _connector='OR'), name='task_batch_cancel_valid'),
        ),
        migrations.AddConstraint(
            model_name='taskbatch',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('assignment_type', 'DEPARTMENT'), models.Q(('source_department_name', ''), _negated=True)), models.Q(models.Q(('assignment_type', 'DEPARTMENT'), _negated=True), ('source_department__isnull', True), ('source_department_name', ''), ('source_department_code', '')), _connector='OR'), name='task_batch_department_valid'),
        ),
        migrations.AddIndex(
            model_name='taskactivity',
            index=models.Index(fields=['task', '-created_at'], name='task_activity_task_idx'),
        ),
        migrations.AddIndex(
            model_name='taskactivity',
            index=models.Index(fields=['batch', '-created_at'], name='task_activity_batch_idx'),
        ),
        migrations.AddIndex(
            model_name='taskactivity',
            index=models.Index(fields=['activity_type', '-created_at'], name='task_activity_type_idx'),
        ),
        migrations.AddConstraint(
            model_name='taskactivity',
            constraint=models.CheckConstraint(condition=models.Q(('task__isnull', False), ('batch__isnull', False), _connector='OR'), name='task_activity_target_valid'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['assigned_to', 'status', 'archived_at', '-created_at'], name='task_assignee_state_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['assigned_department', 'status', 'archived_at', '-created_at'], name='task_department_state_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['batch', 'status'], name='task_batch_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.UniqueConstraint(condition=models.Q(('assigned_to__isnull', False)), fields=('batch', 'assigned_to'), name='task_unique_batch_assignee'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('cancellation_reason', ''), ('cancelled_at__isnull', True), ('completed_at__isnull', False), ('status', 'COMPLETED')), models.Q(('cancelled_at__isnull', False), ('completed_at__isnull', True), ('status', 'CANCELLED'), models.Q(('cancellation_reason', ''), _negated=True)), models.Q(('cancellation_reason', ''), ('cancelled_at__isnull', True), ('completed_at__isnull', True), ('status__in', ('TO_DO', 'IN_PROGRESS', 'BLOCKED'))), _connector='OR'), name='task_status_dates_valid'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(condition=models.Q(('archived_at__isnull', True), ('status__in', ('COMPLETED', 'CANCELLED')), _connector='OR'), name='task_archive_state_valid'),
        ),
        migrations.AddIndex(
            model_name='taskcomment',
            index=models.Index(fields=['task', 'removed_at', 'created_at'], name='task_comment_task_idx'),
        ),
        migrations.AddConstraint(
            model_name='taskcomment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('removal_reason', ''), ('removed_at__isnull', True), ('removed_by__isnull', True)), models.Q(('removed_at__isnull', False), models.Q(('removal_reason', ''), _negated=True)), _connector='OR'), name='task_comment_removed_valid'),
        ),
        migrations.AddIndex(
            model_name='taskreminder',
            index=models.Index(fields=['user', 'cancelled_at', 'remind_at'], name='task_reminder_due_idx'),
        ),
        migrations.AddConstraint(
            model_name='taskreminder',
            constraint=models.UniqueConstraint(fields=('task', 'user', 'remind_at'), name='task_unique_user_reminder'),
        ),
    ]
