# Generated by Django 5.2.6 on 2026-06-29 20:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='taskreminder',
            name='task_unique_user_reminder',
        ),
        migrations.AddConstraint(
            model_name='taskreminder',
            constraint=models.UniqueConstraint(condition=models.Q(('cancelled_at__isnull', True)), fields=('task', 'user', 'remind_at'), name='task_unique_active_user_reminder'),
        ),
        migrations.AddConstraint(
            model_name='taskreminder',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('cancelled_at__isnull', True), ('cancelled_by__isnull', True)), ('cancelled_at__isnull', False), _connector='OR'), name='task_reminder_cancel_valid'),
        ),
    ]
