# Generated by Django 5.2.6 on 2026-07-10 10:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_crm_operations'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PartyBankAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_method', models.CharField(choices=[('BANK_TRANSFER', 'Bank transfer'), ('MOBILE_MONEY', 'Mobile money'), ('OTHER', 'Other')], default='BANK_TRANSFER', max_length=20)),
                ('account_name', models.CharField(max_length=255)),
                ('bank_name', models.CharField(blank=True, max_length=255)),
                ('provider_name', models.CharField(blank=True, max_length=255)),
                ('encrypted_account_number', models.TextField(blank=True, editable=False)),
                ('account_number_hash', models.CharField(blank=True, db_index=True, editable=False, max_length=64)),
                ('account_number_last_four', models.CharField(blank=True, editable=False, max_length=4)),
                ('encrypted_iban', models.TextField(blank=True, editable=False)),
                ('iban_hash', models.CharField(blank=True, db_index=True, editable=False, max_length=64)),
                ('iban_last_four', models.CharField(blank=True, editable=False, max_length=4)),
                ('swift_bic', models.CharField(blank=True, max_length=20)),
                ('currency', models.CharField(blank=True, max_length=3)),
                ('country_code', models.CharField(blank=True, max_length=2)),
                ('verification_status', models.CharField(choices=[('UNVERIFIED', 'Unverified'), ('PENDING', 'Pending verification'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], db_index=True, default='UNVERIFIED', max_length=20)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_bank_accounts_created', to=settings.AUTH_USER_MODEL)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='crm.party')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_bank_accounts_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['party__display_name', '-is_primary', 'account_name'],
                'permissions': [('view_sensitive_partybankaccount', 'Can reveal sensitive CRM bank details'), ('manage_sensitive_partybankaccount', 'Can manage sensitive CRM bank details')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_primary', True)), fields=('party',), name='crm_one_primary_bank_account'), models.UniqueConstraint(condition=models.Q(('account_number_hash', ''), _negated=True), fields=('party', 'account_number_hash'), name='crm_unique_party_account_number'), models.UniqueConstraint(condition=models.Q(('iban_hash', ''), _negated=True), fields=('party', 'iban_hash'), name='crm_unique_party_iban')],
            },
        ),
        migrations.CreateModel(
            name='PartyDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('REGISTRATION', 'Registration'), ('TAX', 'Tax'), ('BANK', 'Bank/payment'), ('CONTRACT', 'Contract'), ('CORRESPONDENCE', 'Correspondence'), ('IDENTITY', 'Identity'), ('QUOTE', 'Quote/supporting record'), ('OTHER', 'Other')], db_index=True, default='OTHER', max_length=30)),
                ('original_filename', models.CharField(max_length=255)),
                ('mime_type', models.CharField(max_length=255)),
                ('size_bytes', models.PositiveBigIntegerField()),
                ('checksum_sha256', models.CharField(db_index=True, max_length=64)),
                ('storage_provider', models.CharField(choices=[('GOOGLE_DRIVE', 'Google Drive'), ('SUPABASE', 'Supabase Storage')], max_length=20)),
                ('external_file_id', models.CharField(max_length=1000)),
                ('external_folder_id', models.CharField(blank=True, max_length=1000)),
                ('storage_path', models.CharField(blank=True, max_length=1500)),
                ('description', models.TextField(blank=True)),
                ('is_confidential', models.BooleanField(db_index=True, default=False)),
                ('verification_status', models.CharField(choices=[('UNVERIFIED', 'Unverified'), ('PENDING', 'Pending verification'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='UNVERIFIED', max_length=20)),
                ('expires_at', models.DateField(blank=True, db_index=True, null=True)),
                ('expiry_notification_key', models.CharField(blank=True, editable=False, max_length=255)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_documents_deleted', to=settings.AUTH_USER_MODEL)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='crm.party')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_documents_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'permissions': [('download_partydocument', 'Can download CRM documents'), ('view_confidential_partydocument', 'Can view confidential CRM documents'), ('manage_confidential_partydocument', 'Can manage confidential CRM documents')],
                'indexes': [models.Index(fields=['party', 'category', 'is_active'], name='crm_document_party_idx'), models.Index(fields=['expires_at', 'is_active'], name='crm_document_expiry_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('party', 'category', 'checksum_sha256'), name='crm_unique_active_document')],
            },
        ),
        migrations.CreateModel(
            name='PartyIdentifier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('identifier_type', models.CharField(choices=[('COMPANY_REGISTRATION', 'Company registration number'), ('TAX_ID', 'Tax identification number'), ('VAT', 'VAT number'), ('IMPORT_EXPORT', 'Import/export number'), ('MARKETPLACE_SELLER', 'Marketplace seller ID'), ('OTHER', 'Other')], db_index=True, max_length=30)),
                ('label', models.CharField(blank=True, max_length=150)),
                ('encrypted_value', models.TextField(editable=False)),
                ('value_hash', models.CharField(db_index=True, editable=False, max_length=64)),
                ('value_last_four', models.CharField(blank=True, editable=False, max_length=4)),
                ('issuing_country', models.CharField(blank=True, max_length=2)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_identifiers_created', to=settings.AUTH_USER_MODEL)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identifiers', to='crm.party')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_identifiers_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['party__display_name', 'identifier_type', 'label'],
                'permissions': [('view_sensitive_partyidentifier', 'Can reveal sensitive CRM party identifiers'), ('manage_sensitive_partyidentifier', 'Can manage sensitive CRM party identifiers')],
                'indexes': [models.Index(fields=['identifier_type', 'value_hash'], name='crm_identifier_lookup_idx')],
                'constraints': [models.UniqueConstraint(fields=('party', 'identifier_type', 'value_hash'), name='crm_unique_party_identifier'), models.CheckConstraint(condition=models.Q(('expiry_date__isnull', True), ('issue_date__isnull', True), ('expiry_date__gte', models.F('issue_date')), _connector='OR'), name='crm_identifier_dates_valid')],
            },
        ),
    ]
